# Generated by Django 4.0.3 on 2022-05-09 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Test',
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listpk', models.CharField(max_length=100, verbose_name='listpk')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('number', models.CharField(max_length=10, verbose_name='学籍番号')),
                ('grade', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=50, verbose_name='学年')),
                ('group', models.CharField(max_length=100, verbose_name='所属')),
                ('se', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=50, verbose_name='性別')),
                ('adre', models.CharField(max_length=100, verbose_name='連絡先(gmail)')),
                ('content', models.TextField(verbose_name='備考')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'リスト',
                'verbose_name_plural': 'リスト',
            },
        ),
        migrations.CreateModel(
            name='BList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('content', models.CharField(max_length=100, verbose_name='概要')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bリスト',
                'verbose_name_plural': 'Bリスト',
            },
        ),
    ]
